// <auto-generated />
using System;
using CardDealer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardDealer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220926171618_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CardDealer.Entities.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Suit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("728d4e4c-6e9c-468e-89ae-eb94f1e45f3f"),
                            Suit = "Hearts",
                            Value = "Two"
                        },
                        new
                        {
                            Id = new Guid("2ad1eff7-4288-4044-aa3f-f66c65016110"),
                            Suit = "Hearts",
                            Value = "Three"
                        },
                        new
                        {
                            Id = new Guid("b00bb6da-91b1-455b-baac-004a27174bd3"),
                            Suit = "Hearts",
                            Value = "Four"
                        },
                        new
                        {
                            Id = new Guid("4e83609e-5388-4f83-8d34-01a8ff3bd711"),
                            Suit = "Hearts",
                            Value = "Five"
                        },
                        new
                        {
                            Id = new Guid("4c8b0f22-cdda-4b03-99ee-01b85892cb5c"),
                            Suit = "Hearts",
                            Value = "Six"
                        },
                        new
                        {
                            Id = new Guid("6fb8a89b-6c2e-49a4-a713-912bede12d65"),
                            Suit = "Hearts",
                            Value = "Seven"
                        },
                        new
                        {
                            Id = new Guid("b1ac65fd-7883-4f96-8dd2-0af122ad1e5d"),
                            Suit = "Hearts",
                            Value = "Eight"
                        },
                        new
                        {
                            Id = new Guid("b3b5cee7-7056-45c8-ae57-ab85b988d5f5"),
                            Suit = "Hearts",
                            Value = "Nine"
                        },
                        new
                        {
                            Id = new Guid("e7c5ab7b-b88f-4597-b26b-f03eb41525f4"),
                            Suit = "Hearts",
                            Value = "Ten"
                        },
                        new
                        {
                            Id = new Guid("2be855cc-12c2-4289-b0a1-2f0085ded079"),
                            Suit = "Hearts",
                            Value = "Jack"
                        },
                        new
                        {
                            Id = new Guid("4c627e17-b83f-4e36-89ab-140678d4b2f3"),
                            Suit = "Hearts",
                            Value = "Queen"
                        },
                        new
                        {
                            Id = new Guid("2616076f-87b7-4afe-86bd-47144b52369a"),
                            Suit = "Hearts",
                            Value = "King"
                        },
                        new
                        {
                            Id = new Guid("15eef474-b429-4bc7-96ea-5bef2723f236"),
                            Suit = "Diamonds",
                            Value = "Two"
                        },
                        new
                        {
                            Id = new Guid("a3265680-1817-4728-bde0-dfaac3446d41"),
                            Suit = "Diamonds",
                            Value = "Three"
                        },
                        new
                        {
                            Id = new Guid("b36c1ff1-1620-4cbf-b609-691f322e360f"),
                            Suit = "Diamonds",
                            Value = "Four"
                        },
                        new
                        {
                            Id = new Guid("d38d9e8d-13bb-4de1-8ee4-5553f3048938"),
                            Suit = "Diamonds",
                            Value = "Five"
                        },
                        new
                        {
                            Id = new Guid("d2e1236b-21e4-46e4-a87f-223a1ffcafb3"),
                            Suit = "Diamonds",
                            Value = "Six"
                        },
                        new
                        {
                            Id = new Guid("2248a359-b28a-4220-a5f1-ad818d441a12"),
                            Suit = "Diamonds",
                            Value = "Seven"
                        },
                        new
                        {
                            Id = new Guid("aa642858-84ae-42a0-a669-cca4ba1b0dcb"),
                            Suit = "Diamonds",
                            Value = "Eight"
                        },
                        new
                        {
                            Id = new Guid("1b296fec-ff31-4bdc-9b30-6dfd598c5678"),
                            Suit = "Diamonds",
                            Value = "Nine"
                        },
                        new
                        {
                            Id = new Guid("421ce75d-1c92-4c6d-90ca-bf544f9535a2"),
                            Suit = "Diamonds",
                            Value = "Ten"
                        },
                        new
                        {
                            Id = new Guid("8ab4f657-fec7-4e6f-a313-bc48714ea812"),
                            Suit = "Diamonds",
                            Value = "Jack"
                        },
                        new
                        {
                            Id = new Guid("7fcfead0-4aad-43dc-bb9d-29003e9e3b88"),
                            Suit = "Diamonds",
                            Value = "Queen"
                        },
                        new
                        {
                            Id = new Guid("11fedebf-cc85-453e-a94e-4714dc35eaf9"),
                            Suit = "Diamonds",
                            Value = "King"
                        },
                        new
                        {
                            Id = new Guid("359ae769-d6c3-416c-8c56-ec9cea601978"),
                            Suit = "Clubs",
                            Value = "Two"
                        },
                        new
                        {
                            Id = new Guid("1b354afe-1c0f-4dca-9a37-62fcfd187881"),
                            Suit = "Clubs",
                            Value = "Three"
                        },
                        new
                        {
                            Id = new Guid("96439203-188d-45a4-981b-1b1ca4cc3ac7"),
                            Suit = "Clubs",
                            Value = "Four"
                        },
                        new
                        {
                            Id = new Guid("352865be-2aa5-45ca-9a84-8f122c6d2038"),
                            Suit = "Clubs",
                            Value = "Five"
                        },
                        new
                        {
                            Id = new Guid("4a68f5ec-3a90-40af-9ee8-c732012f969c"),
                            Suit = "Clubs",
                            Value = "Six"
                        },
                        new
                        {
                            Id = new Guid("283b6bcf-cfa3-47a5-bee9-695b2e89ec85"),
                            Suit = "Clubs",
                            Value = "Seven"
                        },
                        new
                        {
                            Id = new Guid("49e3124c-2991-40ea-832b-593f97f0190d"),
                            Suit = "Clubs",
                            Value = "Eight"
                        },
                        new
                        {
                            Id = new Guid("1f9454e5-184b-4b50-8558-79eb28246817"),
                            Suit = "Clubs",
                            Value = "Nine"
                        },
                        new
                        {
                            Id = new Guid("2b72262e-07d5-4dca-86f0-8bcfe0bf5f20"),
                            Suit = "Clubs",
                            Value = "Ten"
                        },
                        new
                        {
                            Id = new Guid("2324453b-a7e1-498d-9709-167362b84f92"),
                            Suit = "Clubs",
                            Value = "Jack"
                        },
                        new
                        {
                            Id = new Guid("2941ef8a-f6cb-4170-9ea1-73ed82b526e2"),
                            Suit = "Clubs",
                            Value = "Queen"
                        },
                        new
                        {
                            Id = new Guid("40ed4973-b716-49c7-b64b-7d2b364b8652"),
                            Suit = "Clubs",
                            Value = "King"
                        },
                        new
                        {
                            Id = new Guid("576834a8-ba5e-4b74-b932-74a5351cfdb1"),
                            Suit = "Spades",
                            Value = "Two"
                        },
                        new
                        {
                            Id = new Guid("c0c19b50-30f3-4200-8438-45288efe36c0"),
                            Suit = "Spades",
                            Value = "Three"
                        },
                        new
                        {
                            Id = new Guid("bbf77ef9-d458-476c-a17e-c24b2f744bb9"),
                            Suit = "Spades",
                            Value = "Four"
                        },
                        new
                        {
                            Id = new Guid("b3572929-7e6b-4110-965f-ea01233b2492"),
                            Suit = "Spades",
                            Value = "Five"
                        },
                        new
                        {
                            Id = new Guid("240c0d2b-c12f-435f-8a9a-c457d95186ca"),
                            Suit = "Spades",
                            Value = "Six"
                        },
                        new
                        {
                            Id = new Guid("661fb046-f6d1-4a2c-adf2-4cfe27737f9d"),
                            Suit = "Spades",
                            Value = "Seven"
                        },
                        new
                        {
                            Id = new Guid("5f44ca1f-7c96-41f2-9396-5774bf13db9b"),
                            Suit = "Spades",
                            Value = "Eight"
                        },
                        new
                        {
                            Id = new Guid("ee776d52-af07-43bb-a1bd-db7394003712"),
                            Suit = "Spades",
                            Value = "Nine"
                        },
                        new
                        {
                            Id = new Guid("7f4be3ed-281a-48f4-a2c9-72b5ca7bdff8"),
                            Suit = "Spades",
                            Value = "Ten"
                        },
                        new
                        {
                            Id = new Guid("4de9c913-2575-4598-ae1b-2cd2716b8aa2"),
                            Suit = "Spades",
                            Value = "Jack"
                        },
                        new
                        {
                            Id = new Guid("47616579-8831-49f0-8cf8-fcef4aed52b0"),
                            Suit = "Spades",
                            Value = "Queen"
                        },
                        new
                        {
                            Id = new Guid("fcebafef-db36-4086-863b-e0286dffa42a"),
                            Suit = "Spades",
                            Value = "King"
                        });
                });

            modelBuilder.Entity("CardDealer.Entities.Models.Hand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Hands");
                });

            modelBuilder.Entity("CardHand", b =>
                {
                    b.Property<Guid>("CardHandsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CardHandsId", "CardsId");

                    b.HasIndex("CardsId");

                    b.ToTable("CardHand");
                });

            modelBuilder.Entity("CardHand", b =>
                {
                    b.HasOne("CardDealer.Entities.Models.Hand", null)
                        .WithMany()
                        .HasForeignKey("CardHandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardDealer.Entities.Models.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
